# Generated by Django 3.2.5 on 2022-04-18 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(upload_to='', verbose_name=models.ImageField(upload_to='images/'))),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('image1', models.ImageField(upload_to='', verbose_name=models.ImageField(upload_to='images/'))),
                ('image2', models.ImageField(upload_to='', verbose_name=models.ImageField(upload_to='images/'))),
                ('image3', models.ImageField(upload_to='', verbose_name=models.ImageField(upload_to='images/'))),
                ('image4', models.ImageField(upload_to='', verbose_name=models.ImageField(upload_to='images/'))),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_wishlist', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_information.item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemEstore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('image1', models.ImageField(upload_to='', verbose_name=models.ImageField(upload_to='images/'))),
                ('image2', models.ImageField(upload_to='', verbose_name=models.ImageField(upload_to='images/'))),
                ('image3', models.ImageField(upload_to='', verbose_name=models.ImageField(upload_to='images/'))),
                ('image4', models.ImageField(upload_to='', verbose_name=models.ImageField(upload_to='images/'))),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('estore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_information.estore')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HotDeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name=models.ImageField(upload_to='images/'))),
                ('description', models.TextField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
