# Generated by Django 3.2.5 on 2022-04-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotdeals',
            name='category',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
