# Generated by Django 3.2.5 on 2022-05-01 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_information', '0003_auto_20220428_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estore',
            name='following',
        ),
    ]
